version: "3.9"

services:
  backend:
    build:
      context: .
    env_file:
      - .env  
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    depends_on:
      - mailhog

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI (http://localhost:8025)
